name: cypress-test
on:
  push:
    branches:
      - test-allure-report

jobs:
  cypress-test:
    name: testing WEB UI Ghost Drive Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: test-allure-report
      - name: Install dependencies
        uses: cypress-io/github-action@v4
        with:
          # just perform install
          runTests: false
          command: npm install
      - run: yarn lint
      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install: false
          # Cypress tests and config file are in "e2e" folder
          command: |
            npm run cy:run:allure
            npm run allure:generate
      - name: Get artifacts-screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: artifacts/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - name: Get artifacts-video
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: artifacts/videos
